name: Run Scanner

on:
  push: 
    branches: 
      main
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  pull:
    name: Pull
    runs-on: ubuntu-latest
    steps:
      - name: Create App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node LTS
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install Dependencies
        run: pnpm install

      - name: Run script
        run: export LICENSE_BLACKLIST=$(< blacklist.txt) && pnpm dlx tsx src/index.ts
        working-directory: ./
        env:
          GH_APP_ID: ${{ vars.GH_APP_ID }}
          GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          GH_ORG_INSTALLATION_ID: ${{ secrets.GH_ORG_INSTALLATION_ID }}
          GH_ORG_URL: ${{ vars.GH_ORG_URL }}
            